# Generated by Django 5.1.1 on 2025-02-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_candidateprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
