# Generated by Django 5.1.1 on 2025-02-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidateprofile_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='currently',
            field=models.CharField(choices=[('employed', 'Employed'), ('not_employed', 'Not Employed'), ('student', 'Student')], default='not_employed', max_length=15),
        ),
    ]
