# Generated by Django 5.1.1 on 2025-02-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employerprofile_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
