# Generated by Django 5.1.1 on 2025-02-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_employerprofile_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='skills_required',
            field=models.JSONField(default=list),
        ),
    ]
