# Generated by Django 5.1.1 on 2025-02-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_opportunity_skills_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcounter',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
