# Generated by Django 5.1.1 on 2025-02-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_applicationcounter_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
