# Generated by Django 5.1.1 on 2025-02-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_candidateprofile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='description',
        ),
    ]
