# Generated by Django 5.1.1 on 2025-02-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_candidateprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
