# Generated by Django 5.1.1 on 2025-03-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
